### ISSUE TITLE
Unable to compile under Swift 4.1.1 on Raspberry Pi

### ISSUE THREAD

**Issue by rvsrvs** [PureSwift/Bluetooth#38]
I am running the latest Raspbian Stretch on a Pi 3b+ with Swift 4.1.1 installed from https://packagecloud.io/swift-arm/test?page=1 

I upgraded Package.swift to Swift 4, rearranged the directory structure to match, fixed few random incompatibilities (e.g. flatMap -> compactMap, etc) and encountered:
```
swift: /home/linaro/RaspberryPi/buildSwiftOnARM/swift/lib/Serialization/Serialization.cpp:617: TypeID swift::serialization::Serializer::addTypeRef(swift::Type): Assertion `!ty->hasError() && "Serializing error type"' failed.
[snip stack dump]
1.	While serializing type 'τ_0_1'
<unknown>:0: error: unable to execute command: Aborted
<unknown>:0: error: merge-module command failed due to signal 6 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /home/XXXX/Bluetooth/.build/debug.yaml test -v output:

```
This seems to be the same compiler bug as:  https://bugs.swift.org/browse/SR-6754

By playing around I think I have tracked it down to the compiler getting confused on the `default` static var in BluetoothHostControllerInterface, though its not clear why it would.  

When I remove that variable and its definition in the protocol extension, compilation proceeds normally.  

Has anyone else gotten Bluetooth compiling under swift 4.1?

**Comment by colemancda** [comment]
I have it compiling on macOS Swift 4.1 (Xcode 9.3)

**Comment by rvsrvs** [comment]
hmm..  is there a separate branch for that? or are you just saying `swift build` on the existing repo using the Xcode 9.3 command line?  I noticed that doing that caused swift-version to be set to 3 when the build tool emitted the actual commands because the builder recognized the Swift 3 Package manager format which has changed for swift 4.  If you are I suspect you will hit the same problem I do if you change the Package.swift file to use the PM4 structure.

**Comment by colemancda** [comment]
I meant that this codebase builds with the Swift 4.1 compiler but Swift 3.2 language mode.

**Comment by rvsrvs** [comment]
Ah.. ok.  Any plans to do a separate swift4 branch?

**Comment by rvsrvs** [comment]
I can do a PR for that if its helpful.

**Comment by colemancda** [comment]
What would the advantage be? In terms of Swift compiler we support 3.0.2 - 4.1 (Swift 3.0.2 - 3.2). We already support Xcode 9.3 and Swift 4 compiler, but the swiftc parses the code in a backwards compatible mode. Right now Swift 3 is stable on ARM (Linux), Swift 4 is not, so we would lose our major deployment target (IoT devices).

**Comment by colemancda** [comment]
I do appreciate you creating this issue, and you are free to open a branch for Swift 4. I just don't think I can merge it into `master` for a long time (Swift 5?). If you want a Swift 4 only branch, I could try to commit to maintaining it. I still think the compilation error is a Swift compiler bug and a good reason to stick to Swift 3 for the time being.

**Comment by rvsrvs** [comment]
I'm building an IoT project that pulls BluetoothLinux into a swift-nio based server.  I went to swift4  because NIO requires swift4 to build and I can't mix 3 and 4 in one project.  It's awfully cool having a full server that talks BLE for what I'm doing.

I'm happy to maintain my fork for now and check back in when 4.2 lands if you like.

**Comment by rvsrvs** [comment]
FWIW, I'm maintaining the same on BluetoothLinux and will probably do BluetoothDarwin as well.

**Comment by colemancda** [comment]
Thats pretty cool. However with SPM and Xcode (even Carthage) you can mix Swift 3.2 with 4.1, thus my confusion. All the code needs to be compiled with the Swift 4 compiler, but you can mix and match language syntax.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Compatibility.html

**Comment by colemancda** [comment]
Again, feel free to post the links to your forks here and open a PR.

**Comment by colemancda** [comment]
@rvsrvs Feel free to try out our [`hcitool`](https://millertechnologyperu.github.io/hcitool/) to test HCI commands and do stuff like BLE scanning or iBeacons from the command line.

**Comment by rvsrvs** [comment]
hmmm.  I need to look more closely at that.  When I introduced the dependency on BluetoothLinux into my swift4 project on the R/Pi, SPM definitely tried compiling the source in swift4 mode and I couldn't see option to tell it not to so I assumed it was not supported.  

Let me clean things up and I'll post here.

**Comment by rvsrvs** [comment]
Way ahead of you on hcitool. :). Using that as the example for starting to build my custom BLE service.  BTW, this project rocks.  Any of the guys here doing consulting on it use at all?

**Comment by colemancda** [comment]
I can't share specifics, but yes this is currently deployed in commercial products. A couple of the PureSwift libraries are actually. `SwiftFoundation` was used in at least 3 large projects. Right now our focus is on Bluetooth and Android with Swift. Unfortunately, I am not available for consulting, but we are actively maintaining this project for use in commercial projects and any feedback on the codebase for commercial or hobby projects will be addressed in a timely manner so we can use this project bug free, and hopefully the OSS community will contribute features and bug fixes if they find the project useful.

**Comment by hpux735** [comment]
I'm not sure it's a good first issue, when the resolution is "fix the compiler" ;)

`git cherry-pick -m 1  26905602f9832c2861024090b684b586883589e7` is the commit that fixes the compiler.

**Comment by colemancda** [comment]
Closing as the fix for Swift 4 is a compiler patch.
